---
- name: Getting facts
  hosts: all
  become: true
  gather_facts: true

  tasks:
  - name: Apt-get update
    apt:
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: Installing Wireguard server
    package:
      name: 
      - wireguard
      state: present

  - name: Check if privatekey already exists
    stat:
      path: /etc/wireguard/privatekey
    register: privatekey_exists

  - name: Create privatekey
    shell: |
      wg genkey > /etc/wireguard/privatekey
    args:
      executable: /bin/bash
    when: not privatekey_exists.stat.exists
  
  - name: Check if publickey already exists
    stat:
      path: /etc/wireguard/publickey
    register: publickey_exists

  - name: Create publickey
    shell: |
      cat /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey
    args:
      executable: /bin/bash
    when: not publickey_exists.stat.exists

  - name: get remote file contents
    command: "cat /etc/wireguard/privatekey"
    register: privatekey
    
  - name: Copy VPN configs
    template: src=server.conf.j2 dest=/etc/wireguard/wg0.conf mode=770

  - name: Enable service wg-quick@wg0 and ensure it is not masked
    ansible.builtin.systemd:
      name: wg-quick@wg0
      enabled: true
      masked: no
  
  - name: Make sure a service unit is running
    ansible.builtin.systemd:
      state: started
      name: wg-quick@wg0